### ISSUE TITLE
Replace JSDom with Cheerio?

### ISSUE THREAD

**Issue by blakeembrey** [ianstormtaylor/metascraper#6]
JSDOM is kind of heavy here. Would you consider a PR that replaces JSDOM with Cheerio instead? Since it's really only using `getAttribute` and `querySelector` like APIs, maybe use Cheerio for all text parsing use-cases and have a wrapper for the browser `window` use-case that defers to the `document.*` methods?

**Comment by ianstormtaylor** [comment]
Ah interesting. Yeah definitely would consider it. I kind of just used JSDOM because I figured that would be best for consistency on server/browser without having to do anything in the browser case. It seems like Cheerio is much faster and less memory leaky? I don't know a ton about either really.

For the Cheerio solution, we could even potentially bundle jQuery on the browser side and pass a real jQuery object? Or just bundle Cheerio there as well and parse the `innerHtml`?

Open to ideas for what the best solution would look like! Ideally it keeps it nicely parallel in both places, and easy to implement/manage for us at the `metascraper` level. I'm not *super* worried about browser-side file size, since it would mostly be for things like Chrome extensions or other cases I'd think.

**Comment by ianstormtaylor** [comment]
Replaced in `0.1.1`! Way faster too, nice call

**Comment by ianstormtaylor** [comment]
Also, I opted to just keep it to a single code path (no more `browser/server`) since my only valid browser use case so far is for chrome extensions, where the Cheerio filesize isn't the worst. But we could always get smarter later with jQuery or something (dunno if that's even smaller).

**Comment by blakeembrey** [comment]
One code path is awesome 😄 If anything, I'd make a separate endpoint that wraps around `window` and other interfaces later.
